Repository h80r/pi-papers-2021.2, pull requests merged in 2021-12, with the labels that each got.

#47 Pixel neighborhood function
  lib/algorithm/smoothing_functions.dart
Labels: back-end

#48 Apply Mask function
  lib/algorithm/smoothing_functions.dart
Labels: back-end

#49 Replication and Zero solutions
  lib/algorithm/smoothing_functions.dart
Labels: back-end

#64 Support/minor improvements
  lib/algorithm/spatial_functions.dart
  lib/pages/spatial_page.dart
  lib/utils/spatial_enum.dart
  lib/widgets/input/image_selector.dart
  pubspec.lock
Labels: support

#62 Spatial Filtering Page
  lib/algorithm/spatial_functions.dart
  lib/main.dart
  lib/pages/home_page.dart
  lib/pages/spatial_page.dart
  lib/utils/spatial_enum.dart
  lib/widgets/input/image_selector.dart
  lib/widgets/input/styled_checkbox.dart
  pubspec.lock
Labels: front-end

#67 Detecção Roberts Sobel
  lib/algorithm/spatial_functions.dart
  lib/pages/spatial_page.dart
  lib/utils/image_utils.dart
  lib/utils/spatial_enum.dart
Labels: back-end

#68 Unsharp and Highboost Filters
  lib/algorithm/spatial_functions.dart
  lib/utils/spatial_enum.dart
Labels: back-end
