Repository h80r/pi-papers-2021.2, pull requests merged in 2021-11, with the labels that each got.

#3 Initialize project
  .gitignore
  .metadata
  README.md
  analysis_options.yaml
  lib/main.dart
  linux/.gitignore
  linux/CMakeLists.txt
  linux/flutter/CMakeLists.txt
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugin_registrant.h
  linux/flutter/generated_plugins.cmake
  linux/main.cc
  linux/my_application.cc
  linux/my_application.h
  pubspec.lock
  pubspec.yaml
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  web/index.html
  web/manifest.json
Labels: back-end

#14 Instructions
  README.md
  assets/images/clone.png
  assets/images/flutter_doctor.png
  assets/images/github.png
  assets/images/pub_get.png
Labels: support

#22 Tela Inicial
  lib/main.dart
  lib/pages/home_page.dart
  lib/widgets/input/big_button.dart
Labels: front-end

#23 Feature/arithmetic_ops_backend | Implementação de Operações Aritméticas
  lib/algorithm/arithmetic_ops.dart
  lib/main.dart
  lib/pages/arithmethics_page.dart
  lib/pages/test_page.dart
  lib/widgets/input/image_selector.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, back-end

#24 Feature/page arithmethic
  lib/algorithm/arithmetic_functions.dart
  lib/algorithm/geometric_functions.dart
  lib/main.dart
  lib/pages/arithmetic_page.dart
  lib/pages/geometric_page.dart
  lib/widgets/input/image_selector.dart
  lib/widgets/structure/footer.dart
Labels: enhancement, front-end

#30 Componentes do Histograma
  lib/main.dart
  lib/pages/histogram_page.dart
  lib/pages/home_page.dart
  lib/widgets/histogram_graph.dart
  lib/widgets/input/styled_dropdown.dart
  pubspec.lock
  pubspec.yaml
Labels: front-end

#32 Feature/histogram_page
  lib/algorithm/histogram_functions.dart
  lib/main.dart
  lib/pages/histogram_page.dart
  lib/pages/home_page.dart
  lib/widgets/histogram_graph.dart
Labels: enhancement, front-end

#34 Histograma simples
  lib/algorithm/histogram_functions.dart
  lib/pages/histogram_page.dart
Labels: front-end, back-end

#36 Feature/histogram_enhancements
  lib/algorithm/histogram_functions.dart
  lib/pages/histogram_page.dart
Labels: front-end, back-end
